config/routes.rb
Rails.application.routes.draw do
  resources :clientes

  root 'welcome#index'

  post 'clientes/new' 
  post 'welcome/vistarols' 

  get 'welcome/vistarols'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/encuestado.rb
class Encuestado < ActiveRecord::Base
end

app/models/rol.rb
class Rol < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
    @rols = Rol.all
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    
    def cliente_params
      params.require(:cliente).permit(:h1,
      :h2,
      :h3,
      :h4,
      :h5,
      :h6,
      :h7,
      :h8,
      :h9,
      :h10,
      :h11,
      :h12,
      :h13,
      :n1,
      :n2,
      :n3,
      :n4,
      :n5,
      :n6,
      :n7,
      :n8,
      :n9,
      :n10,
      :n11,
      :n12,
      :n13,
      :c1,
      :c2,
      :c3,
      :c4,
      :c5,
      :c6,
      :c7,
      :c8,
      :c9,
      :c10,
      :c11,
      :c12,
      :c13,
      :ph1,
      :pn2,
      :pc3)

      
    end
end

app/controllers/encuestados_controller.rb
class EncuestadosController < ApplicationController

	def index
	end

	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
	end


	def vistarols

		@rols = Rol.all

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clientes/edit.html.erb
<h1>Editing Cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Clientes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= link_to 'Show', cliente %></td>
        <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<%= render 'form' %>

app/views/clientes/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Resultados</title>

    <style>

    body
    {
      background: url('http://wallsdesk.com/wp-content/uploads/2016/08/White-Abstract-Computer-Wallpaper.jpg') fixed !important;
      background-size: cover !important;
      padding: 15px !important;
      margin: 0 !important;
      font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
    }  

    .center {
      text-align: center;
    }

    .bold {
      font-weight: bold;
    }

    .title-show {
      margin: 5% 0 5% 0;
      font-weight: bold;
      font-size: 40px;
      }

      td, th{
        font-size: 20px;
      }

      #notice {
        color: green;
      }

      p {
        font-size: 15px;
        padding: 10px;
      }

      .row-show {
        margin-top: 60px;
      }

    </style>

</head>
<body> 

<div class="container"> 
  <h1 class= "title-show center">Resultados</h1>
    <div class="promedio">
      <% prom1= @cliente.h1 + @cliente.h2 + @cliente.h3 + @cliente.h4 + @cliente.h5 + @cliente.h6 + @cliente.h7 + @cliente.h8 + @cliente.h9 + @cliente.h10 + @cliente.h11 + @cliente.h12 + @cliente.h13 %>
      <% habi = prom1/13 %>
    </div>
    <div class="Necesidades">
    <% prom2= @cliente.n1 + @cliente.n2 + @cliente.n3 + @cliente.n4 + @cliente.n5 + @cliente.n6 + @cliente.n7 + @cliente.n8 + @cliente.n9 + @cliente.n10 + @cliente.n11 + @cliente.n12 + @cliente.n13 %>
    <% nece = prom2/13 %>
    </div>
    <div class="Competencias">
    <% prom3= @cliente.c1 + @cliente.c2 + @cliente.c3 + @cliente.c4 + @cliente.c5 + @cliente.c6 + @cliente.c7 + @cliente.c8 + @cliente.c9 + @cliente.c10 + @cliente.c11 + @cliente.c12 + @cliente.c13 %>
    <% compe = prom3/13 %>
    </div>

  <table class="table table-hover">
    <thead>
      <th class="center">Promedio</th>
      <th class="center">Total</th>
    </thead>
    <tbody>
      <tr>
        <td>Habilidades</td>
        <td class="center"><%= habi %></td>
      </tr>
      <tr>
        <td>Necesidades</td>
        <td class="center"><%= nece %></td>
      </tr>
      <tr>
        <td>Competencias</td>
        <td class="center"><%= compe %></td>
      </tr>
    </tbody>
  </table>
  <div>
    <% temp = 100 %>
    <% temp2 = 100 %>
    <% temp3 = 100 %>
    <% temphabi ="hola" %>
    <% tempnece ="hola" %>
    <% tempcompe ="hola" %>

    <% @rols.each do |rol| %>

         <% if habi < rol.habilidad %>

           <% dif = (habi - rol.habilidad)*(-1) %>

           <% else %>
     
           <%dif = habi - rol.habilidad %>

           <%end%>


           <% if dif < temp %>

           <% temp = dif %>
           <% temphabi = rol.nombre %>
        
           <% end %>
        

           <% if nece < rol.necesidad %>

           <% dif2 = (nece - rol.necesidad)*(-1) %>

           <% else %>
     
           <%dif2 = nece - rol.necesidad %>

           <%end%>



           <% if dif2 < temp2 %>

           <% temp2 = dif2 %>
           <% tempnece = rol.nombre %>
         
           <% end %>


           <% if compe < rol.competencia %>

           <% dif3 = (compe - rol.competencia)*(-1) %>

           <% else %>
     
           <%dif3 = compe - rol.competencia %>

           <%end%>



           <% if dif3 < temp3 %>

           <% temp3 = dif3 %>
           <% tempcompe = rol.nombre %>

           <% end %>
         
    <% end %>
  </div>
   <div class="row row-show">
     <div class="col-md-5">
       <p>En habilidades tu perfil se asemeja al siguiente cargo :</p>
     </div>
     <div class="col-md-4">
       <p class="bold"><%= temphabi %></p>
     </div>
   </div>
   <div class="row">
     <div class="col-md-5">
       <p>En necesidades tu perfil se asemeja al siguiente cargo  :</p>
     </div>
     <div class="col-md-4">
       <p class="bold"><%= tempnece %></p>
     </div>
   </div>
   <div class="row">
     <div class="col-md-5">
       <p>En competencias tu perfil se asemeja al siguiente cargo  :</p>
     </div>
     <div class="col-md-4">
       <p class="bold"><%= tempcompe %></p>
     </div>
   </div>

   <%= link_to 'Volver a Menu', root_path,class:"btn btn-success" %>

</div>

</br>
</br>
</br>







</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proyectogpi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>

	<style>
		body
		{
			background: url('http://wallsdesk.com/wp-content/uploads/2016/08/White-Abstract-Computer-Wallpaper.jpg') fixed !important;
			background-size: cover !important;
			padding: 15px !important;
			margin: 0 !important;
			font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
		}  

    .center {
      text-align: center;
    }

    .foto {
      height: 350px;
      margin-top: 50%;
    }

    .btn-sky {
      color: white;
      font-size: 30px;
      text-decoration: none;
      margin-left: 200px;
    }

    .titleh1 {
      font-weight: bold;
      font-size: 40px;
      padding: 30px;
      margin-top: 36%;
    }

    p {
      margin-top: 20px; 
      font-size: 23px;
      padding: 5px;
    }

    li {
      font-size: 18px;
      padding: 10px;
    }

	</style>
</head>
<body>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <img src="https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/UTEM.svg/896px-UTEM.svg.png" alt="W3Schools.com"" class="foto">
    </div>
    <div class="col-md-6">
      <h1 class="titleh1 center">Proyecto GPI <i>2017</i></h1>
      <p>Integrantes:</p>
      <ul>
        <li>Alvaro Ponce</li>
        <li>Ariel Vargas</li>
      </ul>
     <%= button_to "Ingresar", new_cliente_path , class:"btn btn-primary btn-sky" %>
    </div>
  </div>
</div>




</body>
</html>

app/views/welcome/vistarols.html.erb
 <div class="container">
   <div class="jumbotron">
    <h1 class="center bold">Roles</h1>
  </div>
  <div class="row">
   <div class="col-md-12">
     <table class="table table-striped">
       <thead>
         <tr>
           <th class="center"><b>Nombre</b></th>
           <th class="center"><b>Habilidad</b></th>
           <th class="center"><b>Necesidad</b></th>
           <th class="center"><b>Competencia</b></th>
         </tr>
       </thead>
       <tbody>
         <% @rols.each do |rol| %>
         <tr>
           <td class="center"><%= rol.nombre %></td>
           <td class="center"><%= rol.habilidad %></td>
           <td class="center"><%= rol.necesidad %></td>
           <td class="center"><%= rol.competencia %></td>
         </tr>
         <% end %>
       </tbody>
     </table>
   </div>
 </div>
 <%= link_to 'Volver a Menu', root_path,class:"btn btn-success" %>
</div>